const $=s=>document.querySelector(s),KEY='mini-student-manager-v2';
const old=JSON.parse(localStorage.getItem('mini-student-manager-v1')||'null');let data=JSON.parse(localStorage.getItem(KEY)||'null')||{students:old||[],teachers:[],classes:[]},page='today',filter='all';
const installButton=document.createElement('button');installButton.id='installApp';installButton.className='install-button';installButton.textContent='앱 설치';document.querySelector('.topbar')?.appendChild(installButton);let deferredInstall;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;installButton.hidden=false});installButton.hidden=true;installButton.onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;installButton.hidden=true};window.addEventListener('appinstalled',()=>installButton.hidden=true);if('serviceWorker' in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
const labels={present:'출석',absent:'결석',attention:'주의 필요'};const save=()=>{localStorage.setItem(KEY,JSON.stringify(data));render()};
function exportData(){const backup={format:'mini-student-manager',version:1,exportedAt:new Date().toISOString(),data},blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a'),now=new Date(),pad=value=>String(value).padStart(2,'0');link.href=url;link.download=`학생관리_백업_${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(now.getDate())}.json`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
async function importData(file){if(!file)return;try{const parsed=JSON.parse(await file.text()),incoming=parsed?.format==='mini-student-manager'?parsed.data:parsed;if(!incoming||!Array.isArray(incoming.students)||!Array.isArray(incoming.teachers)||!Array.isArray(incoming.classes))throw new Error('invalid backup');if(!confirm('불러오면 현재 앱의 학생·강사·수업 데이터가 파일 내용으로 바뀝니다. 먼저 현재 데이터도 파일로 저장했나요? 계속할까요?'))return;data={students:incoming.students,teachers:incoming.teachers,classes:incoming.classes};localStorage.setItem(KEY,JSON.stringify(data));render();alert('데이터를 불러왔습니다.')}catch(error){console.error(error);alert('백업 파일을 읽지 못했습니다. 이 앱에서 저장한 JSON 파일인지 확인해 주세요.')}}
function card(item,type){let title=item.name,sub=type==='teachers'?'등록 강사':type==='classes'?`${item.teacher||'강사 미지정'}${item.times?.length?' · '+item.times.join(', '):''}`:`${item.enrollmentNumber?'수강번호 '+item.enrollmentNumber+' · ':''}${item.className||'수업 미지정'}${item.memo?' · '+item.memo:''}`,badge=type==='students'?`<span class="status ${item.status}">${labels[item.status]}</span>`:'',tools=type==='students'?`<div class="student-tools"><button class="record-button attendance ${item.status==='present'?'selected':''}" data-id="${item.id}" data-status="present">출석</button><button class="record-button attendance ${item.status==='absent'?'selected':''}" data-id="${item.id}" data-status="absent">결석</button><button class="record-button progress" data-id="${item.id}">진도</button><button class="record-button homework" data-id="${item.id}">과제</button>${item.status==='absent'?`<button class="record-button sms" data-id="${item.id}">문자</button>`:''}</div>`:'';return `<article class="student-card" data-card-id="${item.id}" data-card-type="${type}"><div class="avatar">${title[0]||'?'}</div><div class="student-info"><strong>${title}</strong><small>${sub}</small>${tools}</div>${badge}<div class="card-actions"><button class="mini-button edit" data-id="${item.id}">✎</button><button class="mini-button remove" data-id="${item.id}">×</button></div></article>`}
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function latestStudentRecord(student,key){return [...(student.records||[])].filter(item=>String(item[key]||'').trim()).sort((a,b)=>b.date.localeCompare(a.date))[0]}
function renderTodayClasses(query){
  const now=new Date(),weekdays=['일요일','월요일','화요일','수요일','목요일','금요일','토요일'],weekday=weekdays[now.getDay()],pad=value=>String(value).padStart(2,'0'),todayKey=`${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(now.getDate())}`;
  const allClasses=data.classes.map(classItem=>({classItem,schedule:(classItem.times||[]).find(time=>time.split(' ')[0]===weekday)})).filter(item=>item.schedule).sort((a,b)=>a.schedule.localeCompare(b.schedule));
  const allStudentIds=new Set(),absentIds=new Set();
  allClasses.forEach(({classItem})=>data.students.filter(student=>student.className===classItem.name).forEach(student=>{allStudentIds.add(student.id);if((student.attendance||[]).find(item=>item.date===todayKey)?.status==='absent')absentIds.add(student.id)}));
  const visibleClasses=allClasses.map(({classItem,schedule})=>{const allMembers=data.students.filter(student=>student.className===classItem.name),classMatches=!query||`${classItem.name} ${classItem.teacher||''} ${schedule}`.toLowerCase().includes(query),members=classMatches?allMembers:allMembers.filter(student=>JSON.stringify(student).toLowerCase().includes(query));return {classItem,schedule,members,classMatches}}).filter(item=>item.classMatches||item.members.length);
  const html=visibleClasses.map(({classItem,schedule,members})=>`<section class="today-class-card"><header><div><strong>${escapeHtml(classItem.name)}</strong><small>${escapeHtml(schedule)}${classItem.teacher?` · ${escapeHtml(classItem.teacher)}`:''}</small></div><span>${members.length}명</span></header><div class="today-class-students">${members.length?members.map(student=>{const progress=latestStudentRecord(student,'progress'),homework=latestStudentRecord(student,'homework'),todayStatus=(student.attendance||[]).find(item=>item.date===todayKey)?.status||'';return `<article class="today-student" data-card-id="${student.id}" data-card-type="students"><div class="today-student-head"><div class="avatar">${escapeHtml(student.name[0]||'?')}</div><div><strong>${escapeHtml(student.name)}</strong><small>${student.enrollmentNumber?`수강번호 ${escapeHtml(student.enrollmentNumber)}`:'수강번호 미등록'}</small></div><span class="status ${todayStatus||'unrecorded'}">${todayStatus?labels[todayStatus]:'미기록'}</span></div><div class="today-latest"><div><span>마지막 진도</span><p>${progress?`${escapeHtml(progress.date)} · ${escapeHtml(progress.progress)}`:'기록 없음'}</p></div><div><span>마지막 과제</span><p>${homework?`${escapeHtml(homework.date)} · ${escapeHtml(homework.homework)}`:'기록 없음'}</p></div></div><div class="today-student-actions"><button type="button" class="record-button sms" data-id="${escapeHtml(student.id)}" aria-label="${escapeHtml(student.name)} 보호자에게 문자 보내기">문자 보내기</button></div></article>`}).join(''):'<p class="today-no-students">등록된 학생이 없습니다.</p>'}</div></section>`).join('');
  return {html,count:visibleClasses.length,classCount:allClasses.length,studentCount:allStudentIds.size,absentCount:absentIds.size,weekday};
}
function render(){
  const q=$('#searchInput').value.trim().toLowerCase(),isToday=page==='today';
  $('#studentFilters').classList.toggle('hidden',page!=='students');$('#studentExcelPanel').classList.toggle('hidden',page!=='students');$('#classManagementTools').classList.toggle('hidden',page!=='classes');$('#openAdd').classList.toggle('hidden',isToday);$('#emptyAdd').classList.toggle('hidden',isToday);$('#studentList').classList.toggle('today-list',isToday);$('#studentStats').classList.toggle('hidden',!['today','students'].includes(page));
  if(isToday){const view=renderTodayClasses(q);$('#pageTitle').textContent='오늘 수업';$('#heroText').textContent=`${view.weekday} 예정 수업과 학생을 확인해요`;$('#searchInput').placeholder='오늘 수업 또는 학생 검색';$('#totalLabel').textContent='오늘 수업';$('#presentLabel').textContent='수업 학생';$('#attentionLabel').textContent='오늘 결석';$('#totalCount').textContent=view.classCount;$('#presentCount').textContent=view.studentCount;$('#attentionCount').textContent=view.absentCount;$('#studentList').innerHTML=view.html;$('#emptyText').textContent=q?'검색 결과가 없어요.':'오늘 등록된 수업이 없어요.';$('#emptyState').classList.toggle('hidden',view.count>0);return}
  $('#pageTitle').textContent=page==='students'?'학생 관리':'수업·강사 관리';$('#heroText').textContent=page==='students'?'학생별 출결과 학습 기록을 관리해요':'강사를 등록하고 수업에 배정해요';$('#searchInput').placeholder=page==='students'?'이름, 수강번호 또는 메모 검색':'강사 또는 수업 검색';$('#totalLabel').textContent='전체 학생';$('#presentLabel').textContent='출석';$('#attentionLabel').textContent='주의 필요';$('#totalCount').textContent=data.students.length;$('#presentCount').textContent=data.students.filter(item=>item.status==='present').length;$('#attentionCount').textContent=data.students.filter(item=>item.status==='attention').length;
  if(page==='classes'){
    const teachers=data.teachers.filter(item=>!q||JSON.stringify(item).toLowerCase().includes(q)),classes=data.classes.filter(item=>!q||JSON.stringify(item).toLowerCase().includes(q));
    const teacherCards=teachers.map(item=>card(item,'teachers')).join(''),classCards=classes.map(item=>card(item,'classes')).join('');
    $('#studentList').innerHTML=`<section class="management-section"><header><h2>등록 강사</h2><span>${data.teachers.length}명</span></header><div class="management-list">${teacherCards||'<p class="management-empty">등록된 강사가 없어요. 위에서 강사를 등록해 주세요.</p>'}</div></section><section class="management-section"><header><h2>등록 수업</h2><span>${data.classes.length}개</span></header><div class="management-list">${classCards||'<p class="management-empty">등록된 수업이 없어요.</p>'}</div></section>`;
    $('#emptyText').textContent=q?'검색 결과가 없어요.':'수업을 등록해 주세요.';$('#emptyState').classList.add('hidden');return;
  }
  let arr=data.students.filter(item=>!q||JSON.stringify(item).toLowerCase().includes(q));if(filter!=='all')arr=arr.filter(item=>item.status===filter);
  $('#studentList').innerHTML=arr.map(item=>card(item,'students')).join('');$('#emptyText').textContent='아직 등록된 학생이 없어요.';$('#emptyAdd').textContent='첫 학생 등록하기';$('#emptyState').classList.toggle('hidden',arr.length>0);
}
function ensureScheduleFields(){const form=$('#classForm');if(!$('#scheduleMode')){const label=document.createElement('label');label.textContent='일정 유형';const mode=document.createElement('select');mode.id='scheduleMode';mode.innerHTML='<option value="same">요일만 다름 (시간 동일)</option><option value="different">요일과 시간이 다름</option>';label.appendChild(mode);form.querySelector('.dialog-head').after(label);mode.onchange=applyScheduleMode} [['classTime1','요일 1'],['classTime2','요일 2']].forEach(([id,text])=>{let time=$('#'+id);if(!time||$('#'+id.replace('Time','Day')))return;if(time.tagName==='SELECT'){const input=document.createElement('input');input.type='time';input.id=id;input.required=id==='classTime1';input.value=time.value;time.replaceWith(input);time=input}const day=document.createElement('select');day.id=id.replace('Time','Day');day.innerHTML=['요일을 선택하세요','월요일','화요일','수요일','목요일','금요일','토요일','일요일'].map(x=>`<option value="${x==='요일을 선택하세요'?'':x}">${x}</option>`).join('');const label=document.createElement('label');label.textContent=text;label.appendChild(day);time.closest('label').before(label);const end=document.createElement('input');end.id=id+'End';end.readOnly=true;end.placeholder='자동 종료 시간';end.className='auto-end';time.closest('label').append(' 종료 ',end);time.onchange=()=>{updateEnd(id);if(id==='classTime1')applyScheduleMode()};});applyScheduleMode()}
function applyScheduleMode(){const same=$('#scheduleMode')?.value==='same';if(!$('#classTime2'))return;$('#classTime2').disabled=same;$('#classTime2').value=same?$('#classTime1').value:'';updateEnd('classTime2')}
function updateEnd(id){const start=$('#'+id).value;if(!start)return $('#'+id+'End').value='';const [h,m]=start.split(':').map(Number),d=new Date(2000,0,1,h,m+90);$('#'+id+'End').value=`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function populateStudentClasses(){let field=$('#classInput');if(field?.tagName==='INPUT'){const select=document.createElement('select');select.id='classInput';select.required=true;field.replaceWith(select);field=select;const label=field.closest('label');if(label?.firstChild)label.firstChild.nodeValue='등록 수업'}field.innerHTML='<option value="">수업을 선택하세요</option>'+data.classes.map(c=>`<option value="${c.name}">${c.name}</option>`).join('')}
function ensureStudentFields(){if(!$('#enrollmentNumberInput')){const label=document.createElement('label');label.textContent='수강번호';const input=document.createElement('input');input.id='enrollmentNumberInput';input.maxLength=30;input.inputMode='numeric';input.placeholder='예: 2026001';label.appendChild(input);$('#classInput').closest('label').before(label)}if(!$('#studentPhone')){const label=document.createElement('label');label.textContent='보호자 연락처';const input=document.createElement('input');input.id='studentPhone';input.type='tel';input.placeholder='010-0000-0000';label.appendChild(input);$('#memoInput').closest('label').before(label)}}
function openAdd(item,targetPage=page){if(page==='today')return;if(targetPage==='students'){populateStudentClasses();ensureStudentFields();$('#studentId').value=item?.id||'';$('#nameInput').value=item?.name||'';$('#enrollmentNumberInput').value=item?.enrollmentNumber||'';$('#classInput').value=item?.className||'';$('#studentPhone').value=item?.phone||'';$('#memoInput').value=item?.memo||'';$('#statusInput').value=item?.status||'present';$('#studentDialog').showModal()}else if(targetPage==='teachers'){ $('#teacherId').value=item?.id||'';$('#teacherName').value=item?.name||'';$('#teacherDialog').showModal()}else{ensureScheduleFields();$('#classId').value=item?.id||'';$('#className').value=item?.name||'';populateTimes();const a=(item?.times||['','']).map(v=>v.split(' '));populateTeachers(item?.teacher||'');$('#classDay1').value=a[0]?.[0]||'';$('#classTime1').value=a[0]?.[1]||'';$('#classDay2').value=a[1]?.[0]||'';$('#classTime2').value=a[1]?.[1]||'';$('#scheduleMode').value=(a[0]?.[1]===a[1]?.[1]?'same':'different');applyScheduleMode();updateEnd('classTime1');updateEnd('classTime2');$('#classDialog').showModal()}}
function populateTeachers(selected=''){$('#classTeacher').innerHTML='<option value="">강사를 선택하세요</option>'+data.teachers.map(t=>`<option value="${t.name}">${t.name}</option>`).join('');$('#classTeacher').value=selected||data.teachers[0]?.name||''}
function populateTimes(){const opts=['','09:00','10:30','12:00','13:30','15:00','16:30','18:00','19:30'].map(t=>`<option value="${t}">${t||'시간을 선택하세요'}</option>`).join('');$('#classTime1').innerHTML=opts;$('#classTime2').innerHTML=opts}
const excelColumns={name:['이름','학생명'],enrollmentNumber:['수강번호'],className:['수업명','등록수업'],phone:['보호자연락처','연락처'],memo:['메모','비고'],status:['상태','오늘의상태','출결']};
const normalizeExcelText=value=>String(value??'').trim();
const normalizeExcelHeader=value=>normalizeExcelText(value).replace(/\s+/g,'').toLowerCase();
function getExcelColumnIndexes(headers){return Object.fromEntries(Object.entries(excelColumns).map(([key,aliases])=>[key,headers.findIndex(header=>aliases.includes(normalizeExcelHeader(header)))]))}
function parseExcelStatus(value){const status=normalizeExcelHeader(value);if(!status)return '';return {present:'present','출석':'present',absent:'absent','결석':'absent',attention:'attention','주의':'attention','주의필요':'attention'}[status]||null}
function downloadStudentTemplate(){if(!window.XLSX)return alert('엑셀 기능을 불러오지 못했습니다. 앱을 새로고침한 후 다시 시도해 주세요.');const sampleClass=data.classes[0]?.name||'등록된 수업명',rows=[['이름','수강번호','수업명','보호자연락처','메모','상태'],['홍길동','2026001',sampleClass,'010-0000-0000','','출석']],sheet=XLSX.utils.aoa_to_sheet(rows),book=XLSX.utils.book_new();sheet['!cols']=[{wch:14},{wch:14},{wch:20},{wch:18},{wch:24},{wch:12}];XLSX.utils.book_append_sheet(book,sheet,'학생등록');XLSX.writeFile(book,'학생_일괄등록_양식.xlsx',{compression:true})}
async function importStudentExcel(file){if(!window.XLSX)return alert('엑셀 기능을 불러오지 못했습니다. 앱을 새로고침한 후 다시 시도해 주세요.');if(!data.classes.length)return alert('학생을 불러오기 전에 수업을 먼저 등록해 주세요.');try{const book=XLSX.read(await file.arrayBuffer(),{type:'array'}),sheet=book.Sheets[book.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false,blankrows:false});if(rows.length<2)return alert('첫 번째 시트에 불러올 학생 내용이 없습니다.');const indexes=getExcelColumnIndexes(rows[0]),missing=[['name','이름'],['enrollmentNumber','수강번호'],['className','수업명']].filter(([key])=>indexes[key]<0).map(([,label])=>label);if(missing.length)return alert(`필수 열이 없습니다: ${missing.join(', ')}`);const classNames=new Map(data.classes.map(item=>[normalizeExcelHeader(item.name),item.name])),studentsByNumber=new Map(data.students.filter(item=>item.enrollmentNumber).map(item=>[normalizeExcelText(item.enrollmentNumber),item])),seenNumbers=new Set(),today=new Date().toISOString().slice(0,10),errors=[];let added=0,updated=0;for(let rowIndex=1;rowIndex<rows.length;rowIndex++){const row=rows[rowIndex];if(row.every(value=>!normalizeExcelText(value)))continue;const get=key=>indexes[key]<0?'':normalizeExcelText(row[indexes[key]]),name=get('name'),enrollmentNumber=get('enrollmentNumber'),classValue=get('className'),className=classNames.get(normalizeExcelHeader(classValue)),parsedStatus=parseExcelStatus(get('status'));if(!name||!enrollmentNumber||!classValue){errors.push(`${rowIndex+1}행: 이름, 수강번호, 수업명을 모두 입력해 주세요.`);continue}if(seenNumbers.has(enrollmentNumber)){errors.push(`${rowIndex+1}행: 수강번호 ${enrollmentNumber}가 파일 안에서 중복됩니다.`);continue}seenNumbers.add(enrollmentNumber);if(!className){errors.push(`${rowIndex+1}행: '${classValue}' 수업이 앱에 등록되어 있지 않습니다.`);continue}if(parsedStatus===null){errors.push(`${rowIndex+1}행: 상태는 출석, 결석, 주의 필요 중 하나로 입력해 주세요.`);continue}const oldStudent=studentsByNumber.get(enrollmentNumber),status=parsedStatus||oldStudent?.status||'present',attendance=[...(oldStudent?.attendance||[])].filter(item=>item.date!==today);attendance.push({date:today,status});const student={id:oldStudent?.id||crypto.randomUUID(),name,enrollmentNumber,className,phone:get('phone')||oldStudent?.phone||'',memo:get('memo')||oldStudent?.memo||'',status,records:oldStudent?.records||[],attendance};if(oldStudent){data.students=data.students.map(item=>item.id===oldStudent.id?student:item);updated++}else{data.students.unshift(student);studentsByNumber.set(enrollmentNumber,student);added++}}if(added||updated){localStorage.setItem(KEY,JSON.stringify(data));render()}const result=[`엑셀 등록 완료`,`새로 등록: ${added}명`,`기존 정보 수정: ${updated}명`];if(errors.length)result.push(`오류: ${errors.length}건`,``,...errors.slice(0,8),errors.length>8?`외 ${errors.length-8}건`:``);alert(result.filter(Boolean).join('\n'))}catch(error){console.error(error);alert('엑셀 파일을 읽지 못했습니다. 양식을 다시 받아 작성해 주세요.')}}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{page=b.dataset.page;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===b));filter='all';render()});$('#openAdd').onclick=()=>openAdd();$('#emptyAdd').onclick=()=>openAdd();$('#openTeacherAdd').onclick=()=>openAdd(null,'teachers');$('#searchInput').oninput=render;document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()});populateTimes();
$('#exportData').onclick=exportData;$('#importData').onclick=()=>$('#backupFileInput').click();$('#backupFileInput').onchange=async event=>{await importData(event.target.files[0]);event.target.value=''};
$('#downloadStudentTemplate').onclick=downloadStudentTemplate;$('#selectStudentExcel').onclick=()=>{if(!data.classes.length)return alert('학생을 불러오기 전에 수업을 먼저 등록해 주세요.');$('#studentExcelInput').click()};$('#studentExcelInput').onchange=async e=>{const file=e.target.files[0];if(file)await importStudentExcel(file);e.target.value=''};
function ensureInfoDialogs(){if($('#activityDialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="activityDialog"><form method="dialog" id="activityForm"><div class="dialog-head"><h2 id="activityTitle">기록</h2><button class="close" type="button" data-activity-close>×</button></div><input type="hidden" id="activityStudent"><input type="hidden" id="activityKind"><label>날짜<input type="date" id="activityDate" required></label><label>내용<textarea id="activityContent" required maxlength="500"></textarea></label><label id="activityApplyClassWrap" class="bulk-record-option hidden"><input type="checkbox" id="activityApplyClass"> 같은 반 전체 학생에게 진도 적용</label><div class="dialog-actions"><button class="secondary" type="button" data-activity-close>취소</button><button class="primary" type="submit">저장하기</button></div></form></dialog><dialog id="detailDialog"><div class="dialog-head"><h2 id="detailTitle">상세 정보</h2><button class="close" onclick="detailDialog.close()">×</button></div><div id="detailBody" class="detail-body"></div><div class="dialog-actions"><button class="primary" onclick="detailDialog.close()">닫기</button></div></dialog>`);$('#activityDialog').querySelectorAll('[data-activity-close]').forEach(button=>button.onclick=()=>$('#activityDialog').close());$('#activityForm').onsubmit=e=>{e.preventDefault();const student=data.students.find(s=>s.id===$('#activityStudent').value),kind=$('#activityKind').value,date=$('#activityDate').value,content=$('#activityContent').value.trim(),applyClass=kind==='progress'&&$('#activityApplyClass').checked;let targets=[student];if(applyClass)targets=data.students.filter(item=>item.className===student.className);const overwritten=targets.filter(target=>(target.records||[]).some(record=>record.date===date&&String(record[kind]||'').trim()));if(overwritten.length&&!confirm(`${date} 날짜에 이미 ${kind==='progress'?'진도':'과제'}가 있는 학생 ${overwritten.length}명의 기록을 새 내용으로 바꿉니다. 계속할까요?`))return;targets.forEach(target=>{target.records=target.records||[];let record=target.records.find(item=>item.date===date);if(!record){record={date,progress:'',homework:''};target.records.push(record)}record[kind]=content});save();$('#activityDialog').close()}}
function openRecord(id,kind){ensureInfoDialogs();const s=data.students.find(x=>x.id===id),today=new Date().toISOString().slice(0,10),record=(s.records||[]).find(r=>r.date===today);$('#activityStudent').value=id;$('#activityKind').value=kind;$('#activityDate').value=today;$('#activityTitle').textContent=`${s.name} · ${kind==='progress'?'진도':'과제'}`;$('#activityContent').value=record?.[kind]||'';$('#activityApplyClassWrap').classList.toggle('hidden',kind!=='progress'||!s.className);$('#activityApplyClass').checked=false;$('#activityDialog').showModal()}
function showStudent(id){
  ensureInfoDialogs();
  const student=data.students.find(x=>x.id===id),today=new Date(),pad=value=>String(value).padStart(2,'0'),dateKey=(year,month,day)=>`${year}-${pad(month+1)}-${pad(day)}`;
  let viewMonth=new Date(today.getFullYear(),today.getMonth(),1),selectedDate=dateKey(today.getFullYear(),today.getMonth(),today.getDate());
  $('#detailTitle').textContent=student.name+' 학생 월간 기록';
  $('#detailBody').innerHTML='<section class="student-calendar"><div class="calendar-toolbar"><button type="button" data-calendar-move="-1" aria-label="이전 달">‹</button><div><strong id="calendarMonthTitle"></strong><small id="calendarMonthStats"></small></div><button type="button" data-calendar-move="1" aria-label="다음 달">›</button></div><div class="calendar-weekdays"><span>일</span><span>월</span><span>화</span><span>수</span><span>목</span><span>금</span><span>토</span></div><div class="calendar-grid" id="calendarGrid"></div><div class="calendar-legend"><span><i class="present"></i>출석</span><span><i class="absent"></i>결석</span><span><b>과</b>과제</span><span><b>메</b>메모</span></div><div id="calendarDayDetail"></div></section>';
  const drawDay=()=>{
    const attendance=(student.attendance||[]).find(item=>item.date===selectedDate),record=(student.records||[]).find(item=>item.date===selectedDate),status=attendance?.status||'';
    $('#calendarDayDetail').innerHTML=`<section class="calendar-day-detail" data-selected-status="${status}"><div class="selected-date-title"><strong>${selectedDate}</strong><span>${status?labels[status]:'출결 기록 없음'}</span></div><div class="calendar-attendance"><button type="button" data-calendar-status="" class="${!status?'active':''}">미기록</button><button type="button" data-calendar-status="present" class="present ${status==='present'?'active':''}">출석</button><button type="button" data-calendar-status="absent" class="absent ${status==='absent'?'active':''}">결석</button></div><label class="day-field">진도<textarea id="calendarProgress" maxlength="500" placeholder="해당 날짜의 진도"></textarea></label>${student.className?'<label class="calendar-bulk-option"><input type="checkbox" id="calendarApplyProgressClass"> 같은 반 전체 학생에게 진도 적용</label>':''}<label class="day-field">과제<textarea id="calendarHomework" maxlength="500" placeholder="해당 날짜의 과제"></textarea></label><label class="day-field">메모<textarea id="calendarMemo" maxlength="500" placeholder="학생에 대한 메모"></textarea></label><button type="button" class="primary calendar-save" id="calendarSave">이 날짜 기록 저장</button><small class="calendar-saved" id="calendarSaved" aria-live="polite"></small></section>`;
    $('#calendarProgress').value=record?.progress||'';
    $('#calendarHomework').value=record?.homework||'';
    $('#calendarMemo').value=record?.memo||'';
  };
  const drawCalendar=()=>{
    const year=viewMonth.getFullYear(),month=viewMonth.getMonth(),monthPrefix=`${year}-${pad(month+1)}`,monthAttendance=(student.attendance||[]).filter(item=>item.date.startsWith(monthPrefix));
    $('#calendarMonthTitle').textContent=`${year}년 ${month+1}월`;
    $('#calendarMonthStats').textContent=`출석 ${monthAttendance.filter(item=>item.status==='present').length} · 결석 ${monthAttendance.filter(item=>item.status==='absent').length}`;
    const firstDay=new Date(year,month,1).getDay(),lastDate=new Date(year,month+1,0).getDate(),cells=[];
    for(let blank=0;blank<firstDay;blank++)cells.push('<span class="calendar-blank"></span>');
    for(let day=1;day<=lastDate;day++){
      const key=dateKey(year,month,day),attendance=(student.attendance||[]).find(item=>item.date===key),record=(student.records||[]).find(item=>item.date===key),flags=[record?.homework?'<b>과</b>':'',record?.memo?'<b>메</b>':''].join('');
      cells.push(`<button type="button" class="calendar-day ${key===selectedDate?'selected':''} ${attendance?.status||''}" data-calendar-date="${key}"><span>${day}</span><i></i><small>${flags}</small></button>`);
    }
    $('#calendarGrid').innerHTML=cells.join('');
    drawDay();
  };
  $('#detailBody').onclick=event=>{
    const move=event.target.closest('[data-calendar-move]');
    if(move){viewMonth=new Date(viewMonth.getFullYear(),viewMonth.getMonth()+Number(move.dataset.calendarMove),1);selectedDate=dateKey(viewMonth.getFullYear(),viewMonth.getMonth(),1);drawCalendar();return}
    const day=event.target.closest('[data-calendar-date]');
    if(day){selectedDate=day.dataset.calendarDate;drawCalendar();return}
    const statusButton=event.target.closest('[data-calendar-status]');
    if(statusButton){const detail=$('.calendar-day-detail'),status=statusButton.dataset.calendarStatus;detail.dataset.selectedStatus=status;detail.querySelectorAll('[data-calendar-status]').forEach(button=>button.classList.toggle('active',button===statusButton));detail.querySelector('.selected-date-title span').textContent=status?labels[status]:'출결 기록 없음';return}
    if(event.target.closest('#calendarSave')){
      const status=$('.calendar-day-detail').dataset.selectedStatus,progress=$('#calendarProgress').value.trim(),homework=$('#calendarHomework').value.trim(),memo=$('#calendarMemo').value.trim(),applyProgressToClass=Boolean(student.className&&$('#calendarApplyProgressClass')?.checked),progressTargets=applyProgressToClass?data.students.filter(item=>item.className===student.className):[student];
      const overwritten=applyProgressToClass?progressTargets.filter(target=>(target.records||[]).some(record=>record.date===selectedDate&&String(record.progress||'').trim())).length:0;
      if(overwritten&&!confirm(`${selectedDate} 날짜에 이미 진도가 있는 같은 반 학생 ${overwritten}명의 기록을 새 내용으로 바꿉니다. 계속할까요?`))return;
      student.attendance=[...(student.attendance||[])].filter(item=>item.date!==selectedDate);
      if(status)student.attendance.push({date:selectedDate,status});
      student.records=student.records||[];
      const oldRecord=student.records.find(item=>item.date===selectedDate);
      if(applyProgressToClass){progressTargets.forEach(target=>{target.records=target.records||[];let record=target.records.find(item=>item.date===selectedDate);if(progress){if(!record){record={date:selectedDate,progress:'',homework:'',memo:''};target.records.push(record)}record.progress=progress}else if(record){record.progress='';if(!record.homework&&!record.memo)target.records=target.records.filter(item=>item!==record)}});const currentRecord=student.records.find(item=>item.date===selectedDate);if(homework||memo||currentRecord?.homework||currentRecord?.memo){const record=currentRecord||{date:selectedDate,progress:'',homework:'',memo:''};if(!currentRecord)student.records.push(record);record.homework=homework;record.memo=memo}}else if(progress||homework||memo){if(oldRecord)Object.assign(oldRecord,{progress,homework,memo});else student.records.push({date:selectedDate,progress,homework,memo})}else if(oldRecord)student.records=student.records.filter(item=>item!==oldRecord);
      if(selectedDate===dateKey(today.getFullYear(),today.getMonth(),today.getDate()))student.status=status||'attention';
      localStorage.setItem(KEY,JSON.stringify(data));render();drawCalendar();$('#calendarSaved').textContent='저장되었습니다.';
    }
  };
  drawCalendar();
  $('#detailDialog').showModal();
}
function showClass(id){ensureInfoDialogs();const c=data.classes.find(x=>x.id===id),members=data.students.filter(s=>s.className===c.name);$('#detailTitle').textContent=c.name+' 학생 목록';$('#detailBody').innerHTML=members.length?members.map(s=>`<article class="record-item"><strong>${s.name}</strong><p>${labels[s.status]||''}</p></article>`).join(''):'<p class="muted">이 수업에 등록된 학생이 없습니다.</p>';$('#detailDialog').showModal()}
function sendSms(id){
  const student=data.students.find(item=>item.id===id);
  if(!student)return;
  const phone=String(student.phone||'').replace(/[^0-9+]/g,'');
  if(!/[0-9]/.test(phone))return alert('학생 정보에 보호자 연락처를 먼저 등록해 주세요.');
  const now=new Date(),pad=value=>String(value).padStart(2,'0'),todayKey=now.getFullYear()+'-'+pad(now.getMonth()+1)+'-'+pad(now.getDate());
  const isAbsent=page==='today'?(student.attendance||[]).some(item=>item.date===todayKey&&item.status==='absent'):student.status==='absent';
  const body=encodeURIComponent('[이다국어] '+student.name+(isAbsent?' 학생이 결석하였습니다. 확인하여 주세요.':' 학생 보호자님, 안녕하세요.'));
  const separator=/iPad|iPhone|iPod/.test(navigator.userAgent)?'&':'?';
  location.href='sms:'+phone+separator+'body='+body;
}
$('#studentList').onclick=e=>{const id=e.target.dataset.id,cardElement=e.target.closest('[data-card-type]'),type=cardElement?.dataset.cardType||page;if(e.target.classList.contains('remove')){if(confirm('삭제할까요?')){const key=page==='classes'&&type==='teachers'?'teachers':page==='classes'?'classes':'students';data[key]=data[key].filter(x=>x.id!==id);save()}return}if(e.target.classList.contains('edit'))return openAdd(data[type].find(x=>x.id===id),type);if(e.target.classList.contains('attendance')){const s=data.students.find(x=>x.id===id),status=e.target.dataset.status,date=new Date().toISOString().slice(0,10);s.status=status;s.attendance=[...(s.attendance||[])].filter(a=>a.date!==date);s.attendance.push({date,status});save();return}if(e.target.classList.contains('progress'))return openRecord(id,'progress');if(e.target.classList.contains('homework'))return openRecord(id,'homework');if(e.target.classList.contains('sms'))return sendSms(id);const selectedCard=e.target.closest('[data-card-id]');if(!selectedCard)return;if(selectedCard.dataset.cardType==='students')showStudent(selectedCard.dataset.cardId);if(selectedCard.dataset.cardType==='classes')showClass(selectedCard.dataset.cardId)};
$('#studentForm').onsubmit=e=>{e.preventDefault();const id=$('#studentId').value,oldStudent=data.students.find(s=>s.id===id),status=$('#statusInput').value,date=new Date().toISOString().slice(0,10),attendance=[...(oldStudent?.attendance||[])].filter(a=>a.date!==date);attendance.push({date,status});const x={id:id||crypto.randomUUID(),name:$('#nameInput').value.trim(),enrollmentNumber:$('#enrollmentNumberInput').value.trim(),className:$('#classInput').value,phone:$('#studentPhone').value.trim(),memo:$('#memoInput').value.trim(),status,records:oldStudent?.records||[],attendance};data.students=id?data.students.map(s=>s.id===id?x:s):[x,...data.students];save();$('#studentDialog').close()};
$('#teacherForm').onsubmit=e=>{e.preventDefault();const id=$('#teacherId').value,x={id:id||crypto.randomUUID(),name:$('#teacherName').value.trim()};data.teachers=id?data.teachers.map(s=>s.id===id?x:s):[x,...data.teachers];save();$('#teacherDialog').close();if(!id&&page==='classes')openAdd(null,'classes')};
$('#classForm').onsubmit=e=>{e.preventDefault();const id=$('#classId').value,x={id:id||crypto.randomUUID(),name:$('#className').value.trim(),teacher:$('#classTeacher').value,times:[[$('#classDay1').value,$('#classTime1').value,$('#classTime1End').value].filter(Boolean).join(' '),[$('#classDay2').value,$('#classTime2').value,$('#classTime2End').value].filter(Boolean).join(' ')].filter(Boolean)};data.classes=id?data.classes.map(s=>s.id===id?x:s):[x,...data.classes];save();$('#classDialog').close()};$('#teacherSubject')?.closest('label')?.remove();$('#todayLabel').textContent=new Intl.DateTimeFormat('ko-KR',{dateStyle:'full'}).format(new Date());render();
